name: Deploy Web to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches:
      - master

    paths:
      - src/Web/MACEL94.github.io/**

permissions:
  contents: write

jobs:
  deploy-web-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v3

      - name: Publish .NET Project
        run: dotnet publish ./src/Web/MACEL94.github.io/MACEL94.github.io.csproj -c Release -o ./src/Web/MACEL94.github.io/release

      - name: Change base-tag in index.html from / to BlazorLinkedinExporter
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorLinkedinExporter\/" \/>/g' ./src/Web/MACEL94.github.io/release/wwwroot/index.html

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./src/Web/MACEL94.github.io/release/wwwroot
          branch: gh-pages
